/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/jwt/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Jwt.Login */
        post: operations["auth_jwt_login_api_auth_jwt_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/jwt/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Jwt.Logout */
        post: operations["auth_jwt_logout_api_auth_jwt_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:Current User */
        get: operations["users_current_user_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Users:Patch Current User */
        patch: operations["users_patch_current_user_api_users_me_patch"];
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:User */
        get: operations["users_user_api_users__id__get"];
        put?: never;
        post?: never;
        /** Users:Delete User */
        delete: operations["users_delete_user_api_users__id__delete"];
        options?: never;
        head?: never;
        /** Users:Patch User */
        patch: operations["users_patch_user_api_users__id__patch"];
        trace?: never;
    };
    "/api/recommendations/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Recommendation Like */
        post: operations["post_recommendation_like_api_recommendations_like_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Library Interests */
        post: operations["post_library_interests_api_library_interests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/mini": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News Mini */
        get: operations["get_news_mini_api_news_mini_get"];
        put?: never;
        /** Create News Mini */
        post: operations["create_news_mini_api_news_mini_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/mini/{news_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete News Mini */
        delete: operations["delete_news_mini_api_news_mini__news_id__delete"];
        options?: never;
        head?: never;
        /** Patch News Mini */
        patch: operations["patch_news_mini_api_news_mini__news_id__patch"];
        trace?: never;
    };
    "/api/news/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News Featured */
        get: operations["get_news_featured_api_news_featured_get"];
        put?: never;
        /** Create News Featured */
        post: operations["create_news_featured_api_news_featured_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/featured/{news_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete News Featured */
        delete: operations["delete_news_featured_api_news_featured__news_id__delete"];
        options?: never;
        head?: never;
        /** Patch News Featured */
        patch: operations["patch_news_featured_api_news_featured__news_id__patch"];
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/hub": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Projects Hub */
        get: operations["get_projects_hub_api_projects_hub_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project By Id */
        get: operations["get_project_by_id_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Patch Project */
        patch: operations["patch_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Project Join */
        post: operations["post_project_join_api_projects__project_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/projects/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Create Column */
        post: operations["admin_create_column_api_admin_projects_columns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/projects/columns/{column_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin Delete Column */
        delete: operations["admin_delete_column_api_admin_projects_columns__column_id__delete"];
        options?: never;
        head?: never;
        /** Admin Update Column */
        patch: operations["admin_update_column_api_admin_projects_columns__column_id__patch"];
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library */
        get: operations["get_library_api_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Library Article */
        post: operations["create_library_article_api_library_articles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Library Article */
        delete: operations["delete_library_article_api_library_articles__article_id__delete"];
        options?: never;
        head?: never;
        /** Patch Library Article */
        patch: operations["patch_library_article_api_library_articles__article_id__patch"];
        trace?: never;
    };
    "/api/admin/library/showcase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Create Showcase */
        post: operations["admin_create_showcase_api_admin_library_showcase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/library/showcase/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin Delete Showcase */
        delete: operations["admin_delete_showcase_api_admin_library_showcase__item_id__delete"];
        options?: never;
        head?: never;
        /** Admin Update Showcase */
        patch: operations["admin_update_showcase_api_admin_library_showcase__item_id__patch"];
        trace?: never;
    };
    "/api/admin/library/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Create Interest */
        post: operations["admin_create_interest_api_admin_library_interests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/library/interests/{interest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin Delete Interest */
        delete: operations["admin_delete_interest_api_admin_library_interests__interest_id__delete"];
        options?: never;
        head?: never;
        /** Admin Update Interest */
        patch: operations["admin_update_interest_api_admin_library_interests__interest_id__patch"];
        trace?: never;
    };
    "/api/admin/library/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Create Tag */
        post: operations["admin_create_tag_api_admin_library_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/library/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin Delete Tag */
        delete: operations["admin_delete_tag_api_admin_library_tags__tag_id__delete"];
        options?: never;
        head?: never;
        /** Admin Update Tag */
        patch: operations["admin_update_tag_api_admin_library_tags__tag_id__patch"];
        trace?: never;
    };
    "/api/profile/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile */
        get: operations["get_my_profile_api_profile_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch My Profile */
        patch: operations["patch_my_profile_api_profile_me_patch"];
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notifications */
        get: operations["get_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Recommendations */
        get: operations["get_dashboard_recommendations_api_dashboard_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Home */
        get: operations["get_dashboard_home_api_dashboard_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArticleTag */
        ArticleTag: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Tone */
            tone: string;
        };
        /** BearerResponse */
        BearerResponse: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** Body_auth_jwt_login_api_auth_jwt_login_post */
        Body_auth_jwt_login_api_auth_jwt_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** DashboardHome */
        DashboardHome: {
            events: components["schemas"]["DashboardHomeEvents"];
            productivity: components["schemas"]["DashboardHomeProductivity"];
            highlightCourse: components["schemas"]["DashboardHomeCourse"];
        };
        /** DashboardHomeCourse */
        DashboardHomeCourse: {
            /** Title */
            title: string;
            /** Imageurl */
            imageUrl: string;
            /** Path */
            path: string;
        };
        /** DashboardHomeEvents */
        DashboardHomeEvents: {
            /** Count */
            count: number;
            /** Deltalabel */
            deltaLabel: string;
        };
        /** DashboardHomeProductivity */
        DashboardHomeProductivity: {
            /** Value */
            value: string;
            /** Deltalabel */
            deltaLabel: string;
        };
        /**
         * ErrorDetail
         * @description Тело ответа HTTPException (например 404).
         */
        ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /** FeaturedNewsItem */
        FeaturedNewsItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /** Description */
            description: string;
            /** Imageurl */
            imageUrl: string;
            /** Ctalabel */
            ctaLabel: string;
            /** Detailsurl */
            detailsUrl: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HubProject */
        HubProject: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Teamname */
            teamName: string;
            /** Updatedlabel */
            updatedLabel: string;
            /** Teamavatarurl */
            teamAvatarUrl: string;
            /** Detailsurl */
            detailsUrl: string;
            /** Visibility */
            visibility?: ("public" | "private") | null;
            /** Ishot */
            isHot?: boolean | null;
        };
        /** IntegrationItem */
        IntegrationItem: {
            /** Id */
            id: string;
            /** Brand */
            brand: string;
            /** Description */
            description: string;
            /** Statuslabel */
            statusLabel: string;
            /** Connectedsince */
            connectedSince: string;
        };
        /** InterestOption */
        InterestOption: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Selected */
            selected: boolean;
        };
        /** InterestOptionCreateBody */
        InterestOptionCreateBody: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
        };
        /** InterestOptionUpdateBody */
        InterestOptionUpdateBody: {
            /** Label */
            label?: string | null;
            /** Selected */
            selected?: boolean | null;
            /** Sortorder */
            sortOrder?: number | null;
        };
        /** InterestsPayload */
        InterestsPayload: {
            /** Interests */
            interests: string[];
            /** Ts */
            ts: number;
        };
        /** JoinRequest */
        JoinRequest: {
            /** Message */
            message?: string | null;
        };
        /** JoinResponse */
        JoinResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Project Id */
            project_id: string;
        };
        /** LibraryArticle */
        LibraryArticle: {
            /** Id */
            id: string;
            /** Tags */
            tags: components["schemas"]["ArticleTag"][];
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Authorname */
            authorName: string;
            /** Authoravatarurl */
            authorAvatarUrl: string;
            /** Interestids */
            interestIds?: string[];
        };
        /** LibraryArticleCreateBody */
        LibraryArticleCreateBody: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Authorname */
            authorName: string;
            /** Authoravatarurl */
            authorAvatarUrl: string;
            /** Tagids */
            tagIds?: string[];
        };
        /** LibraryArticleUpdateBody */
        LibraryArticleUpdateBody: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Authorname */
            authorName?: string | null;
            /** Authoravatarurl */
            authorAvatarUrl?: string | null;
            /** Tagids */
            tagIds?: string[] | null;
        };
        /** LibraryBundle */
        LibraryBundle: {
            /** Showcaseitems */
            showcaseItems: components["schemas"]["LibraryShowcaseItem"][];
            /** Interestoptions */
            interestOptions: components["schemas"]["InterestOption"][];
            /** Articles */
            articles: components["schemas"]["LibraryArticle"][];
        };
        /** LibraryHero */
        LibraryHero: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Updatedlabel */
            updatedLabel: string;
            /** Providerlabel */
            providerLabel: string;
            /** Description */
            description: string;
        };
        /** LibraryShowcaseItem */
        LibraryShowcaseItem: {
            /** Id */
            id: string;
            /** Brandlabel */
            brandLabel: string;
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Imageurl */
            imageUrl: string;
            hero: components["schemas"]["LibraryHero"];
        };
        /** LibraryTagCreateBody */
        LibraryTagCreateBody: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Tone */
            tone: string;
            /** Sortorder */
            sortOrder?: number | null;
        };
        /** LibraryTagUpdateBody */
        LibraryTagUpdateBody: {
            /** Label */
            label?: string | null;
            /** Tone */
            tone?: string | null;
            /** Sortorder */
            sortOrder?: number | null;
        };
        /** LikePayload */
        LikePayload: {
            /**
             * Entity
             * @enum {string}
             */
            entity: "recommendation" | "news";
            /** Id */
            id: string;
            /** Ts */
            ts: number;
        };
        /** NewsFeaturedCreateBody */
        NewsFeaturedCreateBody: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /** Description */
            description: string;
            /** Imageurl */
            imageUrl: string;
            /** Ctalabel */
            ctaLabel: string;
            /** Detailsurl */
            detailsUrl: string;
        };
        /** NewsFeaturedUpdateBody */
        NewsFeaturedUpdateBody: {
            /** Title */
            title?: string | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Description */
            description?: string | null;
            /** Imageurl */
            imageUrl?: string | null;
            /** Ctalabel */
            ctaLabel?: string | null;
            /** Detailsurl */
            detailsUrl?: string | null;
        };
        /** NewsMiniCreateBody */
        NewsMiniCreateBody: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Imageurl */
            imageUrl: string;
            /** Detailsurl */
            detailsUrl: string;
        };
        /** NewsMiniItem */
        NewsMiniItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Imageurl */
            imageUrl: string;
            /** Detailsurl */
            detailsUrl: string;
        };
        /** NewsMiniUpdateBody */
        NewsMiniUpdateBody: {
            /** Title */
            title?: string | null;
            /** Imageurl */
            imageUrl?: string | null;
            /** Detailsurl */
            detailsUrl?: string | null;
        };
        /** NotificationItem */
        NotificationItem: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Datelabel */
            dateLabel: string;
            /** Datecaption */
            dateCaption: string;
            /** Unread */
            unread?: boolean | null;
            /** Authorlabel */
            authorLabel?: string | null;
            /** Authorname */
            authorName?: string | null;
            /** Accenttext */
            accentText?: string | null;
            /** Ctalabel */
            ctaLabel?: string | null;
            /** Path */
            path?: string | null;
        };
        /** OkResponse */
        OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** ParticipantRow */
        ParticipantRow: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Avatarurl */
            avatarUrl: string;
            /** Avatarvariant */
            avatarVariant: string;
            /** Comitid */
            comitId?: string | null;
            /** Timeinproject */
            timeInProject?: string | null;
            /** Role */
            role?: string | null;
            /** Status */
            status?: string | null;
            /** Lasttask */
            lastTask?: string | null;
        };
        /** PersonPreview */
        PersonPreview: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Avatarurl */
            avatarUrl: string;
            /** Avatarvariant */
            avatarVariant: string;
        };
        /** ProductivityBlock */
        ProductivityBlock: {
            /** Value */
            value: string;
            /** Delta */
            delta: string;
        };
        /** ProfileInterest */
        ProfileInterest: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** ProfileMe */
        ProfileMe: {
            /** Displayname */
            displayName?: string | null;
            /** Bio */
            bio?: string | null;
            /** Interests */
            interests?: components["schemas"]["ProfileInterest"][];
        };
        /** ProfileMePatch */
        ProfileMePatch: {
            /** Displayname */
            displayName?: string | null;
            /** Bio */
            bio?: string | null;
            /** Interestids */
            interestIds?: string[] | null;
        };
        /** ProgressBlock */
        ProgressBlock: {
            /** Value */
            value: string;
            /** Percent */
            percent: number;
        };
        /** ProjectColumn */
        ProjectColumn: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Count */
            count: number;
            /** Projects */
            projects: components["schemas"]["HubProject"][];
        };
        /** ProjectCreateBody */
        ProjectCreateBody: {
            /** Id */
            id: string;
            /** Columnid */
            columnId: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Teamname */
            teamName: string;
            /** Updatedlabel */
            updatedLabel: string;
            /** Teamavatarurl */
            teamAvatarUrl: string;
            /** Detailsurl */
            detailsUrl: string;
            /** Visibility */
            visibility?: ("public" | "private") | null;
            /** Ishot */
            isHot?: boolean | null;
            /** Ownername */
            ownerName: string;
            /** Joinlabel */
            joinLabel: string;
            /** Teamcaption */
            teamCaption: string;
            /** Productivitycaption */
            productivityCaption: string;
            /** Progresscaption */
            progressCaption: string;
            /** Todocaption */
            todoCaption: string;
            /** Integrationcaption */
            integrationCaption: string;
            /** Teammemberspreview */
            teamMembersPreview: components["schemas"]["PersonPreview"][];
            productivity: components["schemas"]["ProductivityBlock"];
            progress: components["schemas"]["ProgressBlock"];
            todo: components["schemas"]["TodoBlock"];
            /** Integrations */
            integrations: components["schemas"]["IntegrationItem"][];
            /** Participants */
            participants: components["schemas"]["ParticipantRow"][];
        };
        /** ProjectDetails */
        ProjectDetails: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Ownername */
            ownerName: string;
            /** Detailsurl */
            detailsUrl: string;
            /** Joinlabel */
            joinLabel: string;
            /** Teamcaption */
            teamCaption: string;
            /** Productivitycaption */
            productivityCaption: string;
            /** Progresscaption */
            progressCaption: string;
            /** Todocaption */
            todoCaption: string;
            /** Integrationcaption */
            integrationCaption: string;
            /** Teammemberspreview */
            teamMembersPreview: components["schemas"]["PersonPreview"][];
            productivity: components["schemas"]["ProductivityBlock"];
            progress: components["schemas"]["ProgressBlock"];
            todo: components["schemas"]["TodoBlock"];
            /** Integrations */
            integrations: components["schemas"]["IntegrationItem"][];
            /** Participants */
            participants: components["schemas"]["ParticipantRow"][];
        };
        /** ProjectUpdateBody */
        ProjectUpdateBody: {
            /** Columnid */
            columnId?: string | null;
            /** Code */
            code?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Teamname */
            teamName?: string | null;
            /** Updatedlabel */
            updatedLabel?: string | null;
            /** Teamavatarurl */
            teamAvatarUrl?: string | null;
            /** Detailsurl */
            detailsUrl?: string | null;
            /** Visibility */
            visibility?: ("public" | "private") | null;
            /** Ishot */
            isHot?: boolean | null;
            /** Ownername */
            ownerName?: string | null;
            /** Joinlabel */
            joinLabel?: string | null;
            /** Teamcaption */
            teamCaption?: string | null;
            /** Productivitycaption */
            productivityCaption?: string | null;
            /** Progresscaption */
            progressCaption?: string | null;
            /** Todocaption */
            todoCaption?: string | null;
            /** Integrationcaption */
            integrationCaption?: string | null;
            /** Teammemberspreview */
            teamMembersPreview?: components["schemas"]["PersonPreview"][] | null;
            productivity?: components["schemas"]["ProductivityBlock"] | null;
            progress?: components["schemas"]["ProgressBlock"] | null;
            todo?: components["schemas"]["TodoBlock"] | null;
            /** Integrations */
            integrations?: components["schemas"]["IntegrationItem"][] | null;
            /** Participants */
            participants?: components["schemas"]["ParticipantRow"][] | null;
        };
        /** ProjectsColumnCreate */
        ProjectsColumnCreate: {
            /** Id */
            id: string;
            /** Title */
            title: string;
        };
        /** ProjectsColumnUpdate */
        ProjectsColumnUpdate: {
            /** Title */
            title?: string | null;
            /** Sortorder */
            sortOrder?: number | null;
        };
        /** RecommendationCard */
        RecommendationCard: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /** Image */
            image: string;
            /** Link */
            link: string;
        };
        /** ShowcaseCreateBody */
        ShowcaseCreateBody: {
            /** Id */
            id: string;
            /** Brandlabel */
            brandLabel: string;
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Imageurl */
            imageUrl: string;
            hero: components["schemas"]["LibraryHero"];
        };
        /** ShowcaseUpdateBody */
        ShowcaseUpdateBody: {
            /** Brandlabel */
            brandLabel?: string | null;
            /** Eyebrow */
            eyebrow?: string | null;
            /** Title */
            title?: string | null;
            /** Imageurl */
            imageUrl?: string | null;
            hero?: components["schemas"]["LibraryHero"] | null;
            /** Sortorder */
            sortOrder?: number | null;
        };
        /** TodoBlock */
        TodoBlock: {
            /** Task */
            task: string;
            /** Updatedlabel */
            updatedLabel: string;
        };
        /**
         * UserCreate
         * @description Регистрация: роль с клиента не задаётся (только email/password + safe create).
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean | null;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean | null;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean | null;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "user" | "moderator" | "admin";
        /** UserUpdate */
        UserUpdate: {
            /** Password */
            password?: string | null;
            /** Email */
            email?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Superuser */
            is_superuser?: boolean | null;
            /** Is Verified */
            is_verified?: boolean | null;
            role?: components["schemas"]["UserRole"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_jwt_login_api_auth_jwt_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_jwt_login_api_auth_jwt_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOTIyMWZmYzktNjQwZi00MzcyLTg2ZDMtY2U2NDJjYmE1NjAzIiwiYXVkIjoiZmFzdGFwaS11c2VyczphdXRoIiwiZXhwIjoxNTcxNTA0MTkzfQ.M10bjOe45I5Ncu_uXvOmVV8QxnL-nZfcH96U90JaocI",
                     *       "token_type": "bearer"
                     *     }
                     */
                    "application/json": components["schemas"]["BearerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_jwt_logout_api_auth_jwt_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_current_user_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_patch_current_user_api_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_user_api_users__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_delete_user_api_users__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_patch_user_api_users__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_recommendation_like_api_recommendations_like_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LikePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_library_interests_api_library_interests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterestsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_mini_api_news_mini_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsMiniItem"][];
                };
            };
        };
    };
    create_news_mini_api_news_mini_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsMiniCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsMiniItem"];
                };
            };
            /** @description Уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_news_mini_api_news_mini__news_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет прав */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_news_mini_api_news_mini__news_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsMiniUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsMiniItem"];
                };
            };
            /** @description Нет прав */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_featured_api_news_featured_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedNewsItem"][];
                };
            };
        };
    };
    create_news_featured_api_news_featured_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsFeaturedCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedNewsItem"];
                };
            };
            /** @description Только модератор */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_news_featured_api_news_featured__news_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Только модератор */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_news_featured_api_news_featured__news_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsFeaturedUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedNewsItem"];
                };
            };
            /** @description Только модератор */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetails"];
                };
            };
            /** @description Колонка не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Проект с таким id уже есть */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_projects_hub_api_projects_hub_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectColumn"][];
                };
            };
        };
    };
    get_project_by_id_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetails"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет прав */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetails"];
                };
            };
            /** @description Нет прав */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_project_join_api_projects__project_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinResponse"];
                };
            };
            /** @description Проект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_column_api_admin_projects_columns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectsColumnCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectColumn"];
                };
            };
            /** @description Колонка уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_column_api_admin_projects_columns__column_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                column_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_column_api_admin_projects_columns__column_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                column_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectsColumnUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_library_api_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryBundle"];
                };
            };
        };
    };
    create_library_article_api_library_articles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryArticleCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryArticle"];
                };
            };
            /** @description Неизвестные теги */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Статья уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_library_article_api_library_articles__article_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нет прав */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_library_article_api_library_articles__article_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryArticleUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryArticle"];
                };
            };
            /** @description Неизвестные теги */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Нет прав */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_showcase_api_admin_library_showcase_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShowcaseCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryShowcaseItem"];
                };
            };
            /** @description Уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_showcase_api_admin_library_showcase__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_showcase_api_admin_library_showcase__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShowcaseUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryShowcaseItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_interest_api_admin_library_interests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterestOptionCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestOption"];
                };
            };
            /** @description Уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_interest_api_admin_library_interests__interest_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interest_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_interest_api_admin_library_interests__interest_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interest_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterestOptionUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestOption"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_tag_api_admin_library_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryTagCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleTag"];
                };
            };
            /** @description Уже существует */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_tag_api_admin_library_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_tag_api_admin_library_tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryTagUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleTag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_profile_api_profile_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileMe"];
                };
            };
        };
    };
    patch_my_profile_api_profile_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileMePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileMe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notifications_api_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationItem"][];
                };
            };
        };
    };
    get_dashboard_recommendations_api_dashboard_recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationCard"][];
                };
            };
        };
    };
    get_dashboard_home_api_dashboard_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardHome"];
                };
            };
            /** @description Конфиг главной не задан */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
}
