"""initial_schema

Revision ID: f04f0693ddd6
Revises: 
Create Date: 2026-03-21 11:18:54.330596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f04f0693ddd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_interest_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_like_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('seed_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_table('dashboard_home_snapshot',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('home_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_recommendation',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=2048), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_article',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_avatar_url', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_interest_option',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_showcase_item',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('brand_label', sa.String(length=255), nullable=False),
    sa.Column('eyebrow', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('hero_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_tag',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('tone', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_featured',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('cta_label', sa.String(length=255), nullable=False),
    sa.Column('details_url', sa.String(length=2048), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_mini',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('details_url', sa.String(length=2048), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications_item',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('date_label', sa.String(length=255), nullable=False),
    sa.Column('date_caption', sa.String(length=255), nullable=False),
    sa.Column('unread', sa.Boolean(), nullable=True),
    sa.Column('author_label', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('accent_text', sa.String(length=255), nullable=True),
    sa.Column('cta_label', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=2048), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects_column',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_article_tag',
    sa.Column('article_id', sa.String(length=255), nullable=False),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['library_article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['library_tag.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.create_table('projects_project',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('updated_label', sa.String(length=255), nullable=False),
    sa.Column('team_avatar_url', sa.String(length=2048), nullable=False),
    sa.Column('details_url', sa.String(length=2048), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=True),
    sa.Column('column_id', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['projects_column.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_join_request',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects_project_detail',
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('join_label', sa.String(length=255), nullable=False),
    sa.Column('team_caption', sa.String(length=255), nullable=False),
    sa.Column('productivity_caption', sa.String(length=255), nullable=False),
    sa.Column('progress_caption', sa.String(length=255), nullable=False),
    sa.Column('todo_caption', sa.String(length=255), nullable=False),
    sa.Column('integration_caption', sa.String(length=255), nullable=False),
    sa.Column('detail_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(
        'ix_projects_project_column_sort',
        'projects_project',
        ['column_id', 'sort_order'],
        unique=False,
    )
    op.create_index(
        'ix_library_article_tag_tag_id',
        'library_article_tag',
        ['tag_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_library_article_tag_tag_id', table_name='library_article_tag')
    op.drop_index('ix_projects_project_column_sort', table_name='projects_project')
    op.drop_table('projects_project_detail')
    op.drop_table('analytics_join_request')
    op.drop_table('projects_project')
    op.drop_table('library_article_tag')
    op.drop_table('projects_column')
    op.drop_table('notifications_item')
    op.drop_table('news_mini')
    op.drop_table('news_featured')
    op.drop_table('library_tag')
    op.drop_table('library_showcase_item')
    op.drop_table('library_interest_option')
    op.drop_table('library_article')
    op.drop_table('dashboard_recommendation')
    op.drop_table('dashboard_home_snapshot')
    op.drop_table('analytics_like_event')
    op.drop_table('analytics_interest_event')
    # ### end Alembic commands ###
